issueTrackerURL="https://github.com/cassiancc/Slime-Time/issues"
displayURL="https://modrinth.com/project/slime-time/"
logoFile= "assets/slime_time/icon.png"
authors="cassiancc"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"
rrv_client="cc.cassian.slime.platform.RrvEntrypoint"

[[dependencies.slime_time]]
modId="neoforge"
type="required"
versionRange="[26.1, 26.2)"
ordering="NONE"
side="BOTH"

[[dependencies.slime_time]]
modId="minecraft"
type="required"
versionRange="[26.1, 26.2)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "slime_time.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[modproperties.slime_time."yumi:entrypoints"."yumi:init"]
value = "cc.cassian.slime.SlimeTime"

[modproperties.slime_time."yumi:entrypoints"."yumi:client_init"]
value = "cc.cassian.slime.client.SlimeTimeClient"