modLoader = "javafml"
loaderVersion = "[4,)"

issueTrackerURL="https://github.com/cassiancc/Slime-Time/issues"
displayURL="https://modrinth.com/project/slime-time/"
logoFile= "assets/slime_time/icon.png"
authors="cassiancc"
license="${mod_license}"

[[mods]]
modId="slime_time"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"

[[dependencies.slime_time]]
modId="neoforge"
type="required"
versionRange="[21, )"
ordering="NONE"
side="BOTH"

[[dependencies.slime_time]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "slime_time.mixins.json"
