issueTrackerURL="https://github.com/cassiancc/Springy-Things/issues"
displayURL="https://modrinth.com/project/springy-things/"
logoFile= "/assets/springythings/icon.png"
authors="cassiancc"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description="${mod_description}"

[[dependencies.springythings]]
modId="neoforge"
type="required"
versionRange="[26.1, 26.2)"
ordering="NONE"
side="BOTH"

[[dependencies.springythings]]
modId="minecraft"
type="required"
versionRange="[26.1, 26.2)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "springythings.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[modproperties.springythings."yumi:entrypoints"."yumi:init"]
value = "cc.cassian.springs.SpringyThings"
